<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import IconGlyph from "./IconGlyph.vue";
import { useHostTitle } from "../native-host-attributes";
const props = withDefaults(defineProps<{ open?: boolean; description?: string; size?: "small" | "medium" | "large"; dismissible?: boolean; confirmLabel?: string; cancelLabel?: string }>(), { open: false, description: "", size: "medium", dismissible: true, confirmLabel: "Continue", cancelLabel: "Cancel" });
const title = useHostTitle("Dialog");
const emit = defineEmits<{ close: []; confirm: [] }>(); const dialog = ref<HTMLElement | null>(null);
watch(() => props.open, async (open) => { if (open) { await nextTick(); dialog.value?.focus(); } });
function trap(event: KeyboardEvent) { if (event.key === "Escape" && props.dismissible) { emit("close"); return; } if (event.key !== "Tab" || !dialog.value) return; const nodes = [...dialog.value.querySelectorAll<HTMLElement>("button,[href],[tabindex]:not([tabindex='-1'])")].filter((node) => !node.hasAttribute("disabled")); if (!nodes.length) return; const first = nodes[0], last = nodes.at(-1)!; const active = (dialog.value.getRootNode() as ShadowRoot).activeElement; if (event.shiftKey && active === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && active === last) { event.preventDefault(); first.focus(); } }
</script>
<template><div v-if="open" class="backdrop" @click.self="dismissible && emit('close')"><section ref="dialog" :class="size" role="dialog" aria-modal="true" :aria-label="title" tabindex="-1" @keydown="trap"><header><div><h2>{{ title }}</h2><p v-if="description">{{ description }}</p></div><button v-if="dismissible" type="button" aria-label="Close dialog" @click="emit('close')"><IconGlyph name="close" :size="20" /></button></header><div class="content"><slot></slot></div><footer><slot name="actions"><button type="button" @click="emit('close')">{{ cancelLabel }}</button><button class="primary" type="button" @click="emit('confirm')">{{ confirmLabel }}</button></slot></footer></section></div></template>
<style>
:host { color: var(--osx-text); font-family: var(--osx-font); }.backdrop { position: fixed; inset: 0; z-index: 1250; display: grid; place-items: center; padding: 20px; background: rgba(7,13,17,.42); backdrop-filter: blur(3px); }.backdrop > section { width: min(520px,100%); overflow: hidden; border: 1px solid var(--osx-border); border-radius: 10px; outline: 0; background: var(--osx-surface-raised); box-shadow: var(--osx-shadow); }.backdrop > section.small { width: min(380px,100%); }.backdrop > section.large { width: min(760px,100%); }header { display: flex; justify-content: space-between; gap: 12px; padding: 18px 20px 12px; }h2 { margin: 0; font: 500 23px Georgia,serif; }p { margin: 5px 0 0; color: var(--osx-muted); font-size: 13px; line-height: 1.45; }.content { max-height: min(55vh,520px); overflow: auto; padding: 8px 20px 20px; font-size: 13px; }footer { display: flex; justify-content: flex-end; gap: 8px; padding: 10px 14px; border-top: 1px solid var(--osx-border-soft); background: var(--osx-surface-sunken); }button { min-height: 31px; padding: 5px 13px; border: 1px solid var(--osx-border); border-radius: 7px; color: var(--osx-text); background: linear-gradient(var(--osx-surface-raised),var(--osx-surface-sunken)); font: 700 12px var(--osx-font); cursor: pointer; }header > button { width: 30px; padding: 0; border: 0; background: transparent; color: var(--osx-muted); font-size: 20px; }.primary { color: white; border-color: color-mix(in srgb,var(--osx-accent) 78%,#123); background: linear-gradient(var(--osx-accent-light),var(--osx-accent)); }button:focus-visible { outline: 3px solid var(--osx-focus); outline-offset: 1px; }
</style>
