<script setup lang="ts">
import { computed, ref, watch } from "vue";
const props = withDefaults(defineProps<{ items?: string; value?: string; label?: string; orientation?: "horizontal" | "vertical" }>(), { items: "General,Advanced", value: "", label: "Sections", orientation: "horizontal" });
const emit = defineEmits<{ change: [value: string] }>(); const choices = computed(() => props.items.split(",").map((item) => item.trim()).filter(Boolean)); const current = ref(props.value || choices.value[0] || ""); watch(() => props.value, (value) => { if (value) current.value = value; });
const id = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g,"-");
function select(value: string) { current.value = value; emit("change", value); }
function move(event: KeyboardEvent, index: number) { const keys = props.orientation === "vertical" ? ["ArrowDown","ArrowUp"] : ["ArrowRight","ArrowLeft"]; if (!keys.includes(event.key)) return; event.preventDefault(); const delta = event.key === keys[0] ? 1 : -1; select(choices.value[(index + delta + choices.value.length) % choices.value.length]); }
</script>
<template><section :class="['tabs',orientation]"><div role="tablist" :aria-label="label" :aria-orientation="orientation"><button v-for="(item,index) in choices" :id="`tab-${id(item)}`" :key="item" type="button" role="tab" :aria-selected="item === current" :aria-controls="`panel-${id(item)}`" :tabindex="item === current ? 0 : -1" @click="select(item)" @keydown="move($event,index)">{{ item }}</button></div><div :id="`panel-${id(current)}`" role="tabpanel" :aria-labelledby="`tab-${id(current)}`" tabindex="0"><slot :name="id(current)"><slot></slot></slot></div></section></template>
<style>
:host { display: block; color: var(--osx-text); font-family: var(--osx-font); }.tabs { border: 1px solid var(--osx-border); border-radius: 8px; background: var(--osx-surface-raised); }.tabs > div[role="tablist"] { display: flex; gap: 2px; padding: 6px 8px 0; border-bottom: 1px solid var(--osx-border); background: var(--osx-surface-sunken); }.tabs button { min-height: 31px; padding: 5px 12px; border: 1px solid transparent; border-bottom: 0; border-radius: 6px 6px 0 0; color: var(--osx-muted); background: transparent; font: 700 12px var(--osx-font); cursor: pointer; }.tabs button[aria-selected="true"] { color: var(--osx-text); border-color: var(--osx-border); background: var(--osx-surface-raised); transform: translateY(1px); }.tabs button:focus-visible { outline: 3px solid var(--osx-focus); outline-offset: -2px; }.tabs > div[role="tabpanel"] { min-height: 110px; padding: 16px; outline: 0; font-size: 13px; }.vertical { display: grid; grid-template-columns: max-content minmax(0,1fr); }.vertical > div[role="tablist"] { flex-direction: column; padding: 8px 0 8px 8px; border-right: 1px solid var(--osx-border); border-bottom: 0; }.vertical button { border-right: 0; border-bottom: 1px solid transparent; border-radius: 6px 0 0 6px; }.vertical button[aria-selected="true"] { transform: translateX(1px); }@media (max-width: 480px) { .vertical { grid-template-columns: 1fr; }.vertical > div[role="tablist"] { flex-direction: row; padding: 6px 8px 0; border-right: 0; border-bottom: 1px solid var(--osx-border); }.vertical button { border-right: 1px solid transparent; border-bottom: 0; border-radius: 6px 6px 0 0; } }
</style>
