export type ComponentDoc = {
  description: string;
  example: string;
  props: string[];
  events?: string[];
  slots?: string[];
  tokens?: string[];
  states: string[];
  accessibility: string[];
  keyboard?: string[];
};

const baseTokens = ["--osx-text", "--osx-muted", "--osx-border", "--osx-surface-raised", "--osx-focus"];
const doc = (description: string, example: string, props: string[], states: string[], accessibility: string[], extra: Partial<ComponentDoc> = {}): ComponentDoc => ({ description, example, props, states, accessibility, ...extra });

export const componentDocs: Record<string, ComponentDoc> = {
  "osx-agent-approval": doc("Requests explicit human authorization for a bounded agent action.", '<osx-agent-approval title="Run migration?" risk="medium" scope="npm run migrate"></osx-agent-approval>', ["title: string", "description: string", "risk: low | medium | high", "scope: string", "disabled: boolean"], ["three risk levels", "disabled"], ["Named approval region", "Explicit Allow and Deny controls"], { events: ["approve", "reject"], slots: ["default"], keyboard: ["Tab between actions", "Enter or Space activates"] }),
  "osx-agent-composer": doc("Composes agent requests with command, skill, and context suggestions plus host-controlled model, reasoning, access, attachment, voice, and run state.", '<osx-agent-composer model="Provider · Model" reasoning="High" access-mode="Workspace" placeholder="Ask anything. @ add context, $ use skills, / run commands."></osx-agent-composer>', ["value: string", "placeholder: string", "label: string", "model/reasoning/accessMode: string fallback labels", "modelId/reasoningId/accessModeId: string", "models/reasoningOptions/accessModes: OsxAgentComposerOption[]", "suggestions: OsxAgentComposerSuggestion[]", "suggestionsLoading: boolean", "suggestionsError: string", "contextItems: OsxAgentComposerContextItem[]", "attachments: OsxAgentComposerAttachment[]", "state: idle | submitting | streaming | stopping | error", "statusText/error: string", "busy: boolean", "disabled: boolean", "rows/maxRows: number", "submitShortcut: enter | mod-enter", "allowAttachments/allowVoice: boolean", "attachmentAccept: string"], ["empty", "ready", "suggestions", "selected context", "attachments", "submitting", "streaming", "stopping", "error", "disabled", "responsive"], ["Native textarea remains focused while suggestions use aria-activedescendant", "Named listbox and grouped options", "Live result, selection, removal, and error announcements", "Visible focus, forced-colors, and reduced-motion support", "Host owns discovery, uploads, voice capture, permissions, and execution"], { events: ["input(value)", "submit(value, submissionContext)", "stop", "suggestion-query({ trigger, query })", "suggestion-select(item)", "context-change(items)", "context-remove(item)", "attachment-request({ accept })", "attachment-add(files)", "attachments-change(items)", "attachment-remove(item)", "attachment-retry(item)", "model-change(id, option)", "reasoning-change(id, option)", "access-mode-change(id, option)", "voice-request"], slots: ["tools (legacy)", "leading-actions", "controls", "trailing-actions"], keyboard: ["Enter submits by default", "Shift+Enter adds a newline", "Arrow keys, Home, and End navigate suggestions and option lists", "Enter or Tab selects a suggestion", "Escape closes the active list", "IME composition never submits"] }),
  "osx-agent-message": doc("Presents user, assistant, and system turns with model and lifecycle context.", '<osx-agent-message message-role="assistant" author="Agent" model="Local model">Verified the focused test.</osx-agent-message>', ["messageRole: user | assistant | system", "author: string", "model: string", "timestamp: string", "status: complete | streaming | error"], ["three roles", "streaming", "error"], ["Semantic article per message", "Streaming status is announced"], { slots: ["default"] }),
  "osx-agent-run-status": doc("Shows an agent progressing through plan, work, verification, and completion.", '<osx-agent-run-status phase="verifying" label="Fix tests" detail="3 of 4 phases"></osx-agent-run-status>', ["phase: planning | working | verifying | complete | error", "label: string", "detail: string"], ["planning", "working", "verifying", "complete", "error"], ["Named status region", "aria-busy follows lifecycle"]),
  "osx-alert": doc("Persistent inline feedback for information, success, warning, and error states.", '<osx-alert tone="success" title="Checks passed" description="All tests passed." dismissible></osx-alert>', ["tone: info | success | warning | error", "title: string", "description: string", "dismissible: boolean", "label: string"], ["four tones", "dismissible"], ["Errors use role=alert", "Other tones use role=status"], { events: ["dismiss"], slots: ["default", "actions"] }),
  "osx-artifact": doc("Packages generated files, documents, and code into an actionable output card.", '<osx-artifact title="Migration guide" kind="document" filename="migration.md" version="v2"></osx-artifact>', ["title: string", "description: string", "kind: file | document | code", "filename: string", "version: string", "language: string", "content: string", "href: string", "copyable: boolean", "downloadable: boolean", "openable: boolean", "status: draft | ready | updated"], ["three artifact kinds", "draft", "ready", "updated", "responsive actions"], ["Named artifact article", "Every action has a contextual label", "Preview content wraps or scrolls safely"], { events: ["copy(content)", "download(filename)", "open(href)"], slots: ["default preview"] }),
  "osx-app-shell": doc("Composes the stable regions of an agent or desktop-style application with optional resizable side panels.", '<osx-app-shell app-title="Project Agent" inspector-open resizable>\n  <nav slot="sidebar">Navigation</nav>\n  <section>Workspace</section>\n  <aside slot="inspector">Context</aside>\n</osx-app-shell>', ["appTitle: string", "sidebarWidth: CSS length", "inspectorWidth: CSS length", "inspectorOpen: boolean", "label: string", "resizable: boolean", "sidebarMinWidth/sidebarMaxWidth: number", "inspectorMinWidth/inspectorMaxWidth: number"], ["full container height", "fixed panels", "resizable panels", "inspector open", "inspector closed", "mobile stacked"], ["Named workspace, navigation, and inspector regions", "Fills a definite-height container while tall content scrolls", "Mobile stacking remains reachable when regions exceed the assigned height", "Resize handles expose separator semantics and current pixel values", "Resize handles disappear when panels stack on narrow screens"], { events: ["panel-resize(panel, width)"], slots: ["toolbar", "sidebar", "default", "composer", "inspector", "status"], keyboard: ["Arrow keys resize by 10px", "Home and End choose the configured minimum and maximum"] }),
  "osx-button": doc("OS X-styled action control with optional Lucide icon and native-form submit or reset behavior.", '<osx-button type="submit" variant="primary" icon="download">Download</osx-button>', ["variant: default | primary | danger", "size: small | medium", "type: button | submit | reset", "disabled: boolean", "loading: boolean", "icon: OsxIconName", "iconPosition: leading | trailing"], ["default", "primary", "danger", "leading icon", "trailing icon", "loading", "disabled"], ["Native button", "Submits or resets its nearest form when explicitly typed", "Visible focus ring", "Decorative icon does not duplicate the label"], { events: ["click"], slots: ["default label"], keyboard: ["Enter or Space activates"] }),
  "osx-checkbox": doc("Binary or mixed-state preference control with native-form participation.", '<osx-checkbox name="smoothScrolling" label="Use smooth scrolling" checked></osx-checkbox>', ["checked: boolean", "label: string", "name: string", "value: string", "disabled: boolean", "required: boolean", "indeterminate: boolean"], ["unchecked", "checked", "indeterminate", "disabled", "required"], ["Native checkbox semantics", "Participates in FormData, validation, and reset", "Mixed state is announced"], { events: ["change(checked) — bubbling and composed"], slots: ["default label"], keyboard: ["Space toggles"] }),
  "osx-heading": doc("Semantic headings with a consistent OS X editorial scale.", '<osx-heading level="1" variant="display">Build interfaces with character.</osx-heading>', ["level: 1 | 2 | 3 | 4 | 5 | 6", "variant: display | title | section | label", "align: left | center | right", "tone: default | muted | accent"], ["four scales", "three alignments", "three tones"], ["Renders the requested native heading level", "Visual style is independent from document hierarchy"], { slots: ["default text"] }),
  "osx-copy": doc("Readable body copy with controlled measure, tone, and emphasis.", '<osx-copy size="large" tone="muted">A quiet introduction with a comfortable reading measure.</osx-copy>', ["as: p | span | div", "size: small | medium | large", "tone: default | muted | accent", "weight: regular | medium | bold", "measure: none | narrow | default | wide", "align: left | center | right"], ["three sizes", "three tones", "four measures", "inline span"], ["Uses native paragraph, span, or div semantics", "12px minimum text size", "Long content wraps safely"], { slots: ["default text"] }),
  "osx-citation": doc("Inline source reference chip for grounded agent and RAG responses.", '<osx-citation index="1" source-id="release-notes" title="Node.js release notes"></osx-citation>', ["index: string | number", "label: string", "title: string", "sourceId: string", "href: string", "selected: boolean", "disabled: boolean"], ["button", "link", "selected", "disabled"], ["Contextual accessible name", "Uses native button or anchor semantics", "Selection is not conveyed by color alone"], { events: ["activate(sourceId)"], keyboard: ["Enter or Space activates"] }),
  "osx-data-table": doc("Interactive application data grid with client or server orchestration, search, sorting, selection, pagination, loading, and empty-result recovery.", '<osx-data-table caption="Projects" searchable selectable page-size="5"></osx-data-table>', ["columns: JSON string | OsxDataTableColumn[]", "rows: JSON string | OsxDataTableRow[]", "caption: string", "label: string", "searchable: boolean", "searchPlaceholder: string", "query: string", "compact: boolean", "striped: boolean", "stickyHeader: boolean", "loading: boolean", "loadingLabel: string", "sortKey: string", "sortDirection: ascending | descending", "page: number", "pageSize: number", "pageSizes: comma list | number[]", "serverMode: boolean", "totalRows: number", "selectable: boolean", "selectedKeys: JSON string | array", "rowKey: string", "activatable: boolean", "emptyMessage: string", "noResultsMessage: string"], ["populated", "search results", "no results", "empty", "loading", "sorted", "selected", "paginated", "client mode", "server mode", "compact", "sticky header"], ["Native table and caption semantics", "Search is visibly and programmatically labeled", "Sort direction uses aria-sort", "Selection uses native checkboxes and aria-selected", "Pagination controls have contextual labels", "Loading uses aria-busy and a named status", "Scrollable table region is keyboard reachable"], { events: ["search(query)", "sort(key, direction)", "page-change(page)", "page-size-change(pageSize)", "selection-change(keys)", "row-activate(row, sourceIndex)"], slots: ["actions", "cell-{key} scoped slot", "empty"], keyboard: ["Tab reaches search, sorting, selection, and paging", "Enter or Space activates enabled rows", "Double click activates enabled rows"] }),
  "osx-link": doc("Accessible navigation with focus, external, download, and disabled states.", '<osx-link href="/components.html">Browse every component</osx-link>', ["href: string", "target: _self | _blank | _parent | _top", "rel: string", "external: boolean", "download: boolean | string", "underline: always | hover | none", "disabled: boolean"], ["default", "external", "download", "disabled", "three underline modes"], ["Native anchor semantics", "Safe rel defaults for new tabs", "External mark is decorative"], { slots: ["default label"], keyboard: ["Enter follows the link"] }),
  "osx-diff-viewer": doc("Inspectable unified and split source patches with line-level evidence.", '<osx-diff-viewer file="src/session.ts" view="unified" language="typescript"></osx-diff-viewer>', ["file: string", "patch: string", "view: unified | split", "language: string", "additions: number", "deletions: number", "label: string"], ["unified", "split", "empty patch"], ["Named region", "Diff uses table semantics"], { events: ["view-change(view)", "copy(patch)"], keyboard: ["Arrow keys move through layouts"] }),
  "osx-file-tree": doc("Repository hierarchy with filtering, selection, and Git status markers.", '<osx-file-tree files="src/index.ts,README.md" selected="src/index.ts" filterable></osx-file-tree>', ["files: comma-separated paths", "selected: path", "statuses: JSON map", "label: string", "filterable: boolean"], ["folder open", "folder closed", "selected", "filtered"], ["Tree and treeitem semantics", "Hierarchy levels exposed"], { events: ["select(path)", "toggle(path, open)"], keyboard: ["Enter selects or toggles"] }),
  "osx-icon": doc("Curated Lucide vocabulary with consistent geometry and optical stroke sizing.", '<osx-icon name="sparkle" size="20" label="Agent"></osx-icon>', ["name: OsxIconName", "size: number", "label: string", "strokeWidth: number", "absoluteStrokeWidth: boolean"], ["59 curated icons", "decorative", "meaningful labeled", "16–24px"], ["Unlabeled icons are hidden", "Labeled icons use role=img"], { tokens: ["currentColor"] }),
  "osx-icon-button": doc("Accessible icon-only action with standardized hit areas and Lucide geometry.", '<osx-icon-button icon="settings" label="Open settings"></osx-icon-button>', ["icon: OsxIconName", "label: string (required)", "size: small | medium | large", "variant: default | primary | danger", "disabled: boolean", "pressed: boolean"], ["three sizes", "three variants", "pressed", "disabled"], ["Native button", "Required accessible label", "32px minimum hit area"], { events: ["click"], keyboard: ["Enter or Space activates"] }),
  "osx-progress": doc("Determinate or indeterminate progress feedback.", '<osx-progress value="68" max="100" label="Installing components"></osx-progress>', ["value: number", "max: number", "indeterminate: boolean", "label: string"], ["determinate", "indeterminate", "complete"], ["Progressbar semantics", "Accessible label"]),
  "osx-radio-group": doc("Presents one required or optional choice using native radio semantics, with an optional card treatment.", '<osx-radio-group name="runtime" label="Runtime" options="Local,Cloud" value="Local" variant="cards"></osx-radio-group>', ["options: comma-separated labels | OsxRadioOption[]", "value: string", "label: string", "name: string", "disabled: boolean", "required: boolean", "invalid: boolean", "hint: string", "error: string", "orientation: horizontal | vertical", "variant: default | cards"], ["selected", "unselected", "horizontal", "vertical", "cards", "disabled", "invalid"], ["Native fieldset, legend, and radio inputs", "Participates in FormData, validation, and reset", "Hints and errors are programmatically associated", "State is visible in forced-colors mode"], { events: ["change(value) — bubbling and composed"], keyboard: ["Arrow keys move within the native radio group", "Space selects the focused option"] }),
  "osx-segmented-control": doc("Compact single-selection view control.", '<osx-segmented-control items="General,Controls" value="General" label="Section"></osx-segmented-control>', ["items: comma-separated labels", "value: string", "label: string", "disabled: boolean"], ["selected", "unselected", "disabled"], ["Radiogroup and radio semantics", "Roving focus and forced-colors selection"], { events: ["change(value) — bubbling and composed"], keyboard: ["Arrow keys wrap and move selection", "Home and End select the first and last item"] }),
  "osx-select": doc("Native single-select behavior with structured options, validation, and OS X pop-up styling.", '<osx-select name="appearance" label="Appearance" options="Aqua,Graphite,Panther,Dark Graphite" value="Dark Graphite" required></osx-select>', ["options: comma-separated labels | OsxSelectOption[]", "value: string", "label: string", "name: string", "disabled: boolean", "required: boolean", "invalid: boolean", "hint: string", "error: string"], ["default", "focused", "disabled", "required", "invalid", "disabled option"], ["Native select and label semantics", "Participates in FormData, validation, and reset", "Hints and errors are programmatically associated"], { events: ["change(value) — bubbling and composed"], keyboard: ["Native select behavior"] }),
  "osx-sheet": doc("Window-attached confirmation or focused task dialog.", '<osx-sheet open title="Install component?" description="Adds files to your project."></osx-sheet>', ["open: boolean", "title: string", "description: string", "dismissible: boolean"], ["open", "closed", "non-dismissible"], ["Modal dialog semantics", "Receives focus when opened"], { events: ["close", "confirm"], slots: ["default", "actions"], keyboard: ["Escape closes when dismissible"] }),
  "osx-shimmer": doc("Single flexible loading placeholder with motion preferences respected.", '<osx-shimmer width="72%" height="16px" label="Loading title"></osx-shimmer>', ["width: CSS length", "height: CSS length", "radius: CSS length", "paused: boolean", "label: string"], ["animated", "paused", "reduced motion"], ["Status and aria-busy", "Custom loading label"]),
  "osx-skeleton": doc("Composed text, profile, and card loading shapes.", '<osx-skeleton variant="profile" lines="2"></osx-skeleton>', ["variant: text | card | profile", "lines: 1–8", "animated: boolean", "label: string"], ["text", "profile", "card", "static"], ["Status and aria-busy", "Shapes stay silent"]),
  "osx-spinner": doc("Compact indeterminate activity feedback with accessible labeling and reduced-motion behavior.", '<osx-spinner label="Loading results" show-label></osx-spinner>', ["size: small | medium | large", "tone: default | accent | inverse", "label: string", "showLabel: boolean", "paused: boolean"], ["three sizes", "three tones", "visible label", "paused", "reduced motion"], ["Named status role", "Animation remains understandable with reduced motion"], { slots: ["default visible label"] }),
  "osx-source-list": doc("Finder-style source navigation for application sections.", '<osx-source-list heading="Library" items="Overview,Components,Tokens" value="Components"></osx-source-list>', ["items: comma-separated labels", "value: string", "label: string", "heading: string", "compact: boolean", "icons: JSON item-to-icon map"], ["selected", "unselected", "compact"], ["Named navigation landmark", "Icons remain decorative"], { events: ["change(value)"], keyboard: ["Enter or Space selects"] }),
  "osx-source-panel": doc("Lists grounded response sources and coordinates with inline citation chips.", '<osx-source-panel sources="[{&quot;id&quot;:&quot;1&quot;,&quot;title&quot;:&quot;Release notes&quot;,&quot;url&quot;:&quot;https://example.com&quot;}]"></osx-source-panel>', ["sources: JSON string | OsxSourceItem[]", "title: string", "label: string", "selected: string", "compact: boolean"], ["selected", "unselected", "empty", "compact"], ["Named complementary landmark", "Ordered source list", "Selected state uses aria-pressed"], { events: ["select(sourceId)"], slots: ["default empty state"], keyboard: ["Enter or Space selects"] }),
  "osx-split-view": doc("Primary-detail layout that adapts to narrow screens.", '<osx-split-view primary-size="180px"><nav slot="primary">Files</nav><section>Detail</section></osx-split-view>', ["orientation: horizontal | vertical", "primarySize: CSS length", "label: string"], ["horizontal", "vertical", "mobile stacked"], ["Named group around related panes"], { slots: ["primary", "default"] }),
  "osx-status-bar": doc("Compact readiness, work, and connection context.", '<osx-status-bar label="Connected" status="ready" detail="main"></osx-status-bar>', ["label: string", "status: ready | working | offline", "detail: string"], ["ready", "working", "offline"], ["Status is textual, not color-only"]),
  "osx-table": doc("Responsive data table with native semantics, sortable columns, and safe narrow-screen scrolling.", '<osx-table caption="Recent runs" striped></osx-table>', ["columns: JSON string | OsxTableColumn[]", "rows: JSON string | OsxTableRow[]", "caption: string", "label: string", "compact: boolean", "striped: boolean", "stickyHeader: boolean", "sortKey: string", "sortDirection: ascending | descending", "emptyMessage: string"], ["populated", "empty", "striped", "compact", "sticky header", "sorted ascending", "sorted descending"], ["Native table, caption, column header, and scope semantics", "Scrollable region is keyboard focusable", "Sort direction uses aria-sort"], { events: ["sort(key, direction)"], slots: ["cell-{key} scoped slot", "empty"], keyboard: ["Tab reaches sortable headers", "Enter or Space sorts"] }),
  "osx-terminal": doc("Command, output, lifecycle, and bounded execution controls.", '<osx-terminal command="npm test" cwd="~/project" status="success" duration="1.7s"></osx-terminal>', ["title: string", "command: string", "output: string", "cwd: string", "status: idle | running | success | error", "duration: string", "label: string"], ["idle", "running", "success", "error"], ["Output uses role=log", "Controls have accessible names"], { events: ["rerun(command)", "interrupt", "clear"] }),
  "osx-textarea": doc("Collects multi-line form content with native editing, validation, and resize behavior.", '<osx-textarea name="notes" label="Notes" rows="5" hint="Saved locally" required></osx-textarea>', ["value: string", "label: string", "placeholder: string", "name: string", "rows: number", "maxlength: number", "disabled: boolean", "readonly: boolean", "required: boolean", "invalid: boolean", "hint: string", "error: string", "resize: none | vertical | horizontal | both"], ["empty", "populated", "focused", "disabled", "readonly", "required", "invalid", "four resize modes"], ["Native textarea and label semantics", "Participates in FormData, validation, and reset", "Hints and errors are programmatically associated", "Invalid state includes text"], { events: ["input(value) — bubbling and composed", "change(value) — bubbling and composed"], keyboard: ["Native multiline editing behavior"] }),
  "osx-text-field": doc("Labeled text input with optional Lucide icon and a complete validation contract.", '<osx-text-field name="repository" label="Repository" icon="folder" value="osx-components" hint="Local workspace" required></osx-text-field>', ["value: string", "label: string", "placeholder: string", "type: text | email | password | search | tel | url", "name: string", "autocomplete: string", "maxlength: number", "disabled: boolean", "readonly: boolean", "required: boolean", "invalid: boolean", "hint: string", "error: string", "icon: OsxIconName", "iconPosition: leading | trailing"], ["empty", "populated", "focused", "disabled", "readonly", "required", "invalid", "leading icon", "trailing icon"], ["Participates in FormData, validation, and reset", "Label, hint, and error are associated with the input", "Icon is decorative and does not duplicate the label", "Invalid state includes text"], { events: ["input(value) — bubbling and composed", "change(value) — bubbling and composed"] }),
  "osx-thinking": doc("Discloses a model-provided reasoning summary or progress trace without implying access to hidden chain-of-thought.", '<osx-thinking status="streaming" title="Reasoning" summary="Checking repository evidence…" open>Inspecting the affected call path.</osx-thinking>', ["title: string", "summary: string", "status: idle | streaming | complete | error", "open: boolean", "label: string"], ["collapsed", "expanded", "idle", "streaming", "complete", "error"], ["Native disclosure semantics", "Streaming uses aria-busy and a textual status", "Reduced-motion preference is respected"], { events: ["toggle(open)"], slots: ["default reasoning summary"], keyboard: ["Enter or Space toggles"] }),
  "osx-toast": doc("Transient notification with placement, timeout, and dismissal control.", '<osx-toast open tone="success" title="Copied" message="Snippet copied." placement="top-right"></osx-toast>', ["open: boolean", "tone: info | success | warning | error", "title: string", "message: string", "duration: number", "placement: four corners", "dismissible: boolean", "contained: boolean"], ["four tones", "timed", "persistent"], ["Error announcements assertive", "Other announcements polite"], { events: ["dismiss(manual | timeout)"], slots: ["default"] }),
  "osx-tool-call": doc("Expandable record of one bounded agent tool action.", '<osx-tool-call name="Read" status="success" summary="src/index.ts" duration="14ms" open></osx-tool-call>', ["name: string", "status: queued | running | success | error", "summary: string", "duration: string", "open: boolean"], ["four statuses", "expanded", "collapsed"], ["Native disclosure semantics", "Status is textual"], { slots: ["default"], keyboard: ["Enter or Space toggles"] }),
  "osx-toolbar": doc("Three-region application toolbar.", '<osx-toolbar label="File actions"><strong slot="leading">Files</strong><osx-button slot="trailing">Share</osx-button></osx-toolbar>', ["label: string", "compact: boolean"], ["default", "compact", "mobile wrapped"], ["Named toolbar landmark"], { slots: ["leading", "default", "trailing"] }),
  "osx-toggle": doc("Immediate on/off setting control, distinct from multi-select checkbox behavior.", '<osx-toggle name="agentTools" label="Enable agent tools" description="Allow bounded local actions" checked></osx-toggle>', ["checked: boolean", "label: string", "description: string", "name: string", "value: string", "disabled: boolean", "required: boolean"], ["off", "on", "disabled", "required", "with description"], ["Native checkbox with switch role", "Participates in FormData, validation, and reset", "Description is programmatically associated", "State is visible in forced-colors mode"], { events: ["change(checked) — bubbling and composed"], slots: ["default label"], keyboard: ["Space toggles"] }),
  "osx-window": doc("OS X window chrome with controls, toolbar, content, and footer.", '<osx-window title="Preferences" subtitle="Appearance"><p>Window content</p></osx-window>', ["title: string", "subtitle: string", "active: boolean", "closeable: boolean", "minimizable: boolean", "zoomable: boolean"], ["active", "inactive", "controls hidden", "mobile"], ["Named application window", "Controls have labels"], { events: ["close", "minimize", "zoom"], slots: ["toolbar", "default", "footer"] }),
  "osx-tooltip": doc("Supplemental hover and focus guidance for compact controls.", '<osx-tooltip text="Open settings"><osx-button>Settings</osx-button></osx-tooltip>', ["text: string", "placement: top | right | bottom | left", "open: boolean", "delay: number"], ["hidden", "delayed", "open", "reduced motion"], ["Tooltip role", "Never replaces an action label"], { slots: ["default trigger"] }),
  "osx-popover": doc("Anchored contextual content controlled by its trigger.", '<osx-popover label="Project details"><osx-button slot="trigger">Info</osx-button><p>Details</p></osx-popover>', ["open: boolean", "placement: four sides", "label: string", "dismissible: boolean"], ["open", "closed", "four placements"], ["Named non-modal dialog"], { events: ["open-change(open)", "close"], slots: ["trigger", "default"], keyboard: ["Escape closes"] }),
  "osx-menu": doc("Keyboard-oriented collection of application commands.", '<osx-menu open label="File actions"><osx-menu-item label="New window"></osx-menu-item></osx-menu>', ["open: boolean", "label: string", "placement: start | end"], ["open", "closed"], ["Menu landmark and named collection"], { events: ["close"], slots: ["default menu items"], keyboard: ["Arrow keys move", "Escape closes"] }),
  "osx-menu-item": doc("Action or checkbox row inside an application menu.", '<osx-menu-item label="Show inspector" type="checkbox" checked></osx-menu-item>', ["label: string", "shortcut: string", "disabled: boolean", "checked: boolean", "type: action | checkbox"], ["action", "checked", "unchecked", "disabled"], ["menuitem or menuitemcheckbox role"], { events: ["select", "change(checked)"], slots: ["default label"], keyboard: ["Enter or Space activates"] }),
  "osx-markdown": doc("Renders streaming agent Markdown as safe semantic blocks without injecting model HTML.", '<osx-markdown content="# Result&#10;&#10;The focused test **passed**." streaming></osx-markdown>', ["content: string", "streaming: boolean", "label: string", "codeCopy: boolean"], ["complete", "streaming", "partial code fence", "headings", "lists", "tables", "quotes", "code"], ["Semantic headings, lists, tables, and links", "Unsafe links degrade to text", "No v-html or raw model HTML", "Streaming state uses aria-busy"], { events: ["copy(code, language)"], slots: ["default fallback content"] }),
  "osx-plan": doc("Shows the ordered steps inside an agent run with a state for every step.", '<osx-plan title="Implementation plan" steps="[{&quot;title&quot;:&quot;Inspect repository&quot;,&quot;state&quot;:&quot;done&quot;},{&quot;title&quot;:&quot;Implement change&quot;,&quot;state&quot;:&quot;active&quot;}]"></osx-plan>', ["steps: JSON string | OsxPlanStep[]", "title: string", "label: string", "compact: boolean", "showProgress: boolean"], ["pending", "active", "done", "failed", "skipped", "empty", "compact"], ["Ordered-list semantics", "Active step uses aria-current", "Every state has text and an icon"], { slots: ["default empty state"] }),
  "osx-tabs": doc("Related content panels with roving keyboard selection.", '<osx-tabs items="Overview,API" value="Overview"><p slot="overview">Overview</p><p slot="api">API</p></osx-tabs>', ["items: comma-separated labels", "value: string", "label: string", "orientation: horizontal | vertical"], ["horizontal", "vertical", "selected panel"], ["tablist, tab, and tabpanel semantics"], { events: ["change(value)"], slots: ["default", "named panel IDs"], keyboard: ["Arrow keys select adjacent tabs"] }),
  "osx-dialog": doc("Centered modal with focus management and controlled actions.", '<osx-dialog open title="Publish?" description="Creates a public version."></osx-dialog>', ["open: boolean", "title: string", "description: string", "size: small | medium | large", "dismissible: boolean", "confirmLabel: string", "cancelLabel: string"], ["three sizes", "open", "non-dismissible"], ["Modal dialog semantics", "Focus enters on open"], { events: ["close", "confirm"], slots: ["default", "actions"], keyboard: ["Escape closes", "Tab remains inside"] }),
  "osx-ecosystem-card": doc("Transparent first-party discovery for products that belong to the same ecosystem.", '<osx-ecosystem-card name="Aperta" category="Code comprehension" description="Turn generated code into understanding." href="https://aperta-six.vercel.app/" action-label="Explore Aperta" mark="A"></osx-ecosystem-card>', ["name: string", "category: string", "description: string", "href: string", "actionLabel: string", "mark: string", "provenance: string", "trackingId: string", "tone: neutral | info | success | warning", "compact: boolean", "external: boolean"], ["full", "compact", "four tones", "internal destination", "external destination"], ["Named recommendation article", "Destination uses native anchor semantics", "External destinations receive safe rel values", "No analytics or network requests are made by the component"], { events: ["activate({ name, href, trackingId })"], slots: ["mark", "default description", "provenance", "action"], keyboard: ["Enter follows the destination"] }),
  "osx-empty-state": doc("Zero-data guidance with an optional recovery action.", '<osx-empty-state title="No snippets" description="Save one to find it here." action-label="Browse" icon="inbox"></osx-empty-state>', ["title: string", "description: string", "actionLabel: string", "icon: OsxIconName"], ["informational", "actionable"], ["Named section", "Text explains the recovery path"], { events: ["action"], slots: ["icon", "default", "actions"] }),
  "osx-badge": doc("Compact status, count, or category label.", '<osx-badge tone="success" dot>Ready</osx-badge>', ["tone: neutral | info | success | warning | danger", "size: small | medium", "label: string", "dot: boolean"], ["five tones", "two sizes", "dot"], ["Status remains textual, not color-only"], { slots: ["default"] }),
  "osx-avatar": doc("Person or agent identity with initials, image fallback, and presence.", '<osx-avatar name="Susan Kare" status="online" size="44"></osx-avatar>', ["name: string", "src: URL", "alt: string", "size: number", "status: none | online | busy | offline"], ["initials", "image", "fallback", "presence"], ["Image role and accessible name", "Presence has a text label"]),
};

for (const item of Object.values(componentDocs)) item.tokens ??= baseTokens;

export function frameworkExample(tag: string, framework: "HTML" | "Vue" | "React" | "Svelte"): string {
  const markup = componentDocs[tag]?.example ?? `<${tag}></${tag}>`;
  const setup = 'import { registerOsxComponents } from "@vraxis/osx-components";\nimport "@vraxis/osx-components/theme.css";';
  if (framework === "HTML") return `<script type="module">\n  ${setup.replaceAll("\n", "\n  ")}\n  registerOsxComponents();\n</script>\n\n${markup}`;
  if (framework === "Vue") return `<script setup lang="ts">\nimport { onMounted } from "vue";\n${setup}\nonMounted(registerOsxComponents);\n</script>\n\n<template>\n  ${markup.replaceAll("\n", "\n  ")}\n</template>`;
  if (framework === "React") return `${setup}\nregisterOsxComponents();\n\nexport function Example() {\n  return (${markup.replace(/\b(open|checked|disabled|dismissible|filterable|indeterminate|contained)>/g, '$1="true">')});\n}`;
  return `<script lang="ts">\n  import { onMount } from "svelte";\n  ${setup.replaceAll("\n", "\n  ")}\n  onMount(registerOsxComponents);\n</script>\n\n${markup}`;
}
