import {
  Activity, BookOpen, Bot, Boxes, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  Circle, CircleDashed, Clock, Code2, Command, Copy, CornerDownLeft, Download, Ellipsis,
  ExternalLink, Eye, EyeOff, File, FileCode, FileText, FlaskConical, Folder, FolderOpen,
  GitBranch, Grid2X2, Inbox, Info, LayoutDashboard, ListChecks, LoaderCircle, Lock, LockOpen,
  Menu, Minus, Palette, PanelLeft, Pencil, Play, Plus, RotateCw, Search, Send, Settings,
  Sparkles, Square, SquareStop, Terminal, Trash2, TriangleAlert, Upload, User, X,
} from "@lucide/vue";

export const iconRegistry = {
  activity: Activity,
  book: BookOpen,
  bot: Bot,
  boxes: Boxes,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-dashed": CircleDashed,
  clock: Clock,
  code: Code2,
  command: Command,
  copy: Copy,
  "corner-down-left": CornerDownLeft,
  download: Download,
  ellipsis: Ellipsis,
  external: ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-code": FileCode,
  "file-text": FileText,
  flask: FlaskConical,
  folder: Folder,
  "folder-open": FolderOpen,
  "git-branch": GitBranch,
  grid: Grid2X2,
  inbox: Inbox,
  info: Info,
  dashboard: LayoutDashboard,
  "list-checks": ListChecks,
  loader: LoaderCircle,
  lock: Lock,
  unlock: LockOpen,
  menu: Menu,
  minus: Minus,
  palette: Palette,
  panel: PanelLeft,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  refresh: RotateCw,
  search: Search,
  send: Send,
  settings: Settings,
  sparkle: Sparkles,
  square: Square,
  stop: SquareStop,
  terminal: Terminal,
  trash: Trash2,
  warning: TriangleAlert,
  upload: Upload,
  user: User,
  close: X,
} as const;

export type OsxIconName = keyof typeof iconRegistry;
export const iconNames = Object.keys(iconRegistry) as OsxIconName[];
